#!/usr/bin/env python3
"""Render frontier/CERTIFICATE-REACH.md: where the fractional certificate can still go.

The instrument has a ceiling that depends only on ``n`` and the direction net --
``ceil(sqrt(n)) / (1 + D)``, derived in ``sqpack.fractional.certificate.ceiling_side``
-- and a second cap that depends on the case: its best known packing, scaled into the
container, refutes every certificate above ``U * max(cos d + sin d) / (1 + D)``, ``d``
running over each tilt's offset from its nearest net direction (`packing_side_cap`,
derived at n = 11 in X-014). The smaller of the two is the ``limit``, and joining it
against the frontier's own bounds answers the question a planner actually has, which
is not "how does the method work" but "which case should the next core run".

Four verdicts come out of the join, and each says something different:

  foreclosed   the limit sits at or below the case's existing lower bound, so no
               certificate of this shape can ever improve it. The ceiling forecloses
               exactly the cases whose value is the grid bound ceil(sqrt(n)), which is
               where the refuting grid of ceil(sqrt(n))^2 B-squares fits; the cap
               forecloses a case whose lower bound already reaches it, which a solved
               case with a tilt inventory always does, since the cap sits strictly
               below its own packing.
  packing      the limit clears the best known packing, so the method is not what
               limits this case: the gap to that packing is the whole prize. Only a
               case with no tilt inventory reads this way, because a cap never clears
               the packing it is built from.
  ceiling      the ceiling lands between the two, so it caps the prize below the gap.
  cap          the packing-side cap lands below the ceiling and between the two.

The figure to rank on is the last column, which is the most a certificate could add
to the case's lower bound. It is an upper bound on the prize and not a forecast: what
a search actually reaches is set by the covering value at that side, which is lower.

A second join adds what the record now shows about that gap between prize and
reach: the packing-limited certificates land within 0.001 of the same fraction of
their cases' best known packings. Ceiling-limited certificates are excluded from that
comparison, because their ratio measures the method's own ceiling rather than a
packing. How many rows are on each side is read from the corpus and never written
down here -- a retained rung that gains enough side moves from one side to the other,
which is what happened when `T-021` raised the n = 20 package to 97/20 and turned a
three-point regularity into a two-point one. The regularity is measured, not proved,
and the document says so plainly where it appears -- see `measured_attainment` and
`predicted_reach` for where the two figures it produces, `ratio` and `predicted`,
come from.

Usage:
    uv run --frozen python -m devtools.render_certificate_reach
    uv run --frozen python -m devtools.render_certificate_reach --check
"""

from __future__ import annotations

import argparse
import json
import math
import pathlib
import textwrap
from fractions import Fraction
from itertools import pairwise

from strif import atomic_output_file

from sqpack.fractional.certificate import (
    ceiling_side_for_net,
    grid_refutation_order,
    least_size_certified,
)
from sqpack.yamlio import load_yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
REPO = ROOT.parent
FRONTIER = ROOT / "frontier"
CASES = ROOT / "cases"
COVERING_VALUES = FRONTIER / "covering-values.yaml"
OUT = FRONTIER / "CERTIFICATE-REACH.md"

BANNER = (
    "<!-- GENERATED by devtools.render_certificate_reach from frontier/n-*.md, "
    "frontier/covering-values.yaml and sqpack.fractional.certificate. Do not edit by "
    "hand. -->"
)

# Massaccesi's net, which every retained certificate uses: 181 half-tangents from 0 to
# a rational just above tan(pi/8). D is about T / K, so refining the net raises the
# ceiling only as fast as K grows.
ANGLE_LIMIT = Fraction(207107, 500000)
DIRECTION_STEPS = 180
NET = tuple(ANGLE_LIMIT * k / DIRECTION_STEPS for k in range(DIRECTION_STEPS + 1))


def largest_half_gap_tangent(half_tangents: tuple[Fraction, ...]) -> Fraction:
    """``D`` for a net: the expression `ceiling_side_for_net` takes its supremum over."""
    return max((right - left) / (1 + left * right) for left, right in pairwise(half_tangents))


def net_directions_deg(half_tangents: tuple[Fraction, ...]) -> tuple[float, ...]:
    """Each net direction as the angle, in degrees, its rotation turns through.

    ``sqpack.fractional.model.rotation_from_half_tangent`` turns a half-tangent ``t``
    into the exact rotation by ``2 arctan t``; this is that angle as a float, for the
    one place in this document where a direction is compared against a record's tilt
    rather than decided exactly.
    """
    return tuple(math.degrees(2 * math.atan(tangent)) for tangent in half_tangents)


def fold_tilt(tilt_deg: float) -> float:
    """A tilt reduced to ``[0, 45]`` by the symmetries the net relies on.

    A square is its own image under a quarter turn, so a tilt is read modulo 90; the
    container's diagonal reflection, which ``Condition 1`` makes available, sends
    ``theta`` to ``90 - theta`` and folds ``(45, 90)`` onto ``(0, 45)``. A negative
    tilt folds the same way: ``-36.6`` reads as ``53.4`` modulo 90 and then as
    ``36.6``. The reduction is done in ``Fraction`` so that it is exact; only the
    trigonometry that follows it rounds.
    """
    reduced = Fraction(tilt_deg) % 90
    if reduced > 45:
        reduced = 90 - reduced
    return float(reduced)


def containment_factor(tilt_deg: float, directions_deg: tuple[float, ...]) -> float:
    """``cos d + sin d`` for a tilt's offset ``d`` from the nearest net direction.

    A closed ``B``-square turned by ``d`` from a square of side ``lambda`` fits inside
    it exactly when ``lambda >= B (cos d + sin d)``, and strictly inside when the
    inequality is strict: the containment step behind ``Condition 4``.
    """
    folded = fold_tilt(tilt_deg)
    offset = math.radians(min(abs(folded - direction) for direction in directions_deg))
    return math.cos(offset) + math.sin(offset)


def packing_side_cap(
    upper: float,
    tilts_deg: list[float],
    half_tangents: tuple[Fraction, ...],
    shrink: Fraction | None = None,
) -> float:
    """``U * max(cos d + sin d) / (1 + D)``: where the best known packing refutes the net.

    The grid behind ``ceiling_side`` is one packing, and the case's best known packing
    is another that refutes certificates the same way. Take it at its side ``U`` with
    tilt inventory ``tilts_deg`` and scale it by ``lambda = L / U < 1`` into a
    container of side ``L``. Each scaled square has side ``lambda`` and sits at some
    tilt ``theta``; fold ``theta`` onto the net's arc (`fold_tilt`) and let ``d`` be
    its offset from the nearest net direction. A closed ``B``-square at that net
    direction fits about the same centre exactly when ``lambda >= B (cos d + sin d)``,
    and strictly inside when the inequality is strict. So for
    ``L > U B max(cos d + sin d)``, the maximum over the inventory, the scaled packing
    holds ``n`` pairwise disjoint closed ``B``-squares at net directions; ``Condition 5``
    gives each mass at least ``1``, the total is at least ``n``, and ``Condition 2``
    forbids that. No certificate with shrink ``B`` exists above that side, whatever
    its atoms and weights.

    With ``shrink`` given, that side is the value returned. Without it, ``Condition 4``'s
    ``B < 1 / (1 + D)`` is taken to its supremum, as `ceiling_side_for_net` does over
    `ceiling_side`, and the result is ``U max(cos d + sin d) / (1 + D)``: a supremum
    that no certificate attains, and always strictly below ``U``, because ``d`` never
    exceeds the half-gap while ``cos d + sin d < 1 + tan d`` past ``d = 0``. The
    argument is X-014's (``campaign/explorations/X-014-closing-from-both-ends.md``),
    made at ``n = 11``.

    The record's side and tilts are floats and so is the trigonometry; the net, the
    shrink and the final product are exact. An inventory of ``[0]`` has factor exactly
    ``1``, so a grid packing at side ``ceil(sqrt(n))`` returns `ceiling_side_for_net`'s
    value bit for bit.
    """
    if not tilts_deg:
        raise ValueError("a packing's tilt inventory cannot be empty")
    if shrink is not None and shrink <= 0:
        raise ValueError(f"shrink {shrink} is not positive")
    directions = net_directions_deg(half_tangents)
    factor = Fraction(max(containment_factor(tilt, directions) for tilt in tilts_deg))
    if shrink is None:
        shrink = 1 / (1 + largest_half_gap_tangent(half_tangents))
    return float(Fraction(upper) * shrink * factor)


def case_record(path: pathlib.Path) -> dict:
    """The ``packing`` block of one frontier file's front matter."""
    document = load_yaml(path.read_text(encoding="utf-8").split("---\n")[1])
    return document["packing"]


def tilt_inventory(reported_upper: dict | None) -> list[float] | None:
    """``tilt_angles_deg`` from a ``reported_upper_bound`` block, as floats.

    The list holds the distinct tilts of the best known packing in degrees, signed as
    the geometry was imported (n = 17 carries ``-36.62...``); ``null`` means no
    geometry was imported, and reads as ``None`` here so that no cap is invented.
    """
    if reported_upper is None or reported_upper.get("tilt_angles_deg") is None:
        return None
    return [float(tilt) for tilt in reported_upper["tilt_angles_deg"]]


def cases() -> list[dict]:
    """One row per frontier case with a verified lower bound, verdict included.

    ``bound`` names which of ``ceiling`` and ``cap`` is the ``limit`` -- ``cap`` only
    where it sits strictly below the ceiling, so a grid packing whose cap equals its
    ceiling reads ``ceiling`` -- and ``verdict`` reads the limit against the case's
    own two bounds.
    """
    rows = []
    for path in sorted(FRONTIER.glob("n-*.md")):
        n = int(path.stem.split("-")[1])
        record = case_record(path)
        lower = record.get("verified_lower_bound")
        if not lower or lower.get("value") is None:
            continue
        low = float(lower["value"])
        upper = record.get("reported_upper_bound")
        up = float(upper["value"]) if upper and upper.get("value") is not None else None
        tilts = tilt_inventory(upper)
        ceiling = float(ceiling_side_for_net(n, NET))
        cap = packing_side_cap(up, tilts, NET) if up is not None and tilts is not None else None
        if cap is not None and cap < ceiling:
            bound, limit = "cap", cap
        else:
            bound, limit = "ceiling", ceiling
        if limit <= low:
            verdict, prize = "foreclosed", 0.0
        elif up is not None and limit >= up:
            # Clamped because the two endpoints are parsed from different records: a
            # case whose packing sits exactly at its lower bound must read +0.0000,
            # never a negative zero from the last bit of a float subtraction.
            verdict, prize = "packing", max(up - low, 0.0)
        else:
            verdict, prize = bound, max(limit - low, 0.0)
        rows.append(
            {
                "n": n,
                "order": grid_refutation_order(n),
                "lower": low,
                "upper": up,
                "tilts": tilts,
                "ceiling": ceiling,
                "cap": cap,
                "limit": limit,
                "bound": bound,
                "verdict": verdict,
                "prize": prize,
            }
        )
    return rows


def load_certificate(path: pathlib.Path) -> tuple[dict, Fraction]:
    """A certificate record and the mass recomputed from its own atoms.

    The recomputation is the point: a certificate's mass is what its atoms sum to,
    and the stored ``total_mass`` field is a convenience that can go stale against
    them. Here it is checked rather than trusted, because every figure this document
    keys off that mass -- which case a certificate moves first (`least_size_certified`),
    and the feasible masses the reported-value table quotes -- would be wrong together
    if the field and the atoms ever disagreed. `devtools.check_rung_figures` makes the
    same check for the figures the results register quotes; this is the same rule at
    the one other place the mass is read.
    """
    record = json.loads(path.read_text())
    total_mass = Fraction(str(record["total_mass"]))
    atom_mass = sum((Fraction(str(atom[2])) for atom in record["atoms"]), Fraction())
    if atom_mass != total_mass:
        try:
            display = path.relative_to(ROOT)
        except ValueError:
            display = path
        raise ValueError(
            f"{display}: declared total_mass {total_mass} does not equal atom sum {atom_mass}"
        )
    return record, atom_mass


def covering_value_register() -> list[dict]:
    """The rows of ``frontier/covering-values.yaml``, in register order.

    One row per ``(n, side, site set)``: what the record reports for the restricted
    covering program, with ``converged`` a field rather than a phrase. The objectives
    are quotations -- from `results.yaml`'s own accounts of T-018, T-019 and T-020,
    from agenda-019's target list, and from X-013's confirmation of six of them -- and
    nothing here can recompute them: no covering-search run log or solver checkpoint
    was retained for any of them. What can be recomputed is the certificate frozen at
    that side, where one is, and that is a feasible mass rather than an optimum.
    """
    document = load_yaml(COVERING_VALUES.read_text(encoding="utf-8"))
    return document["values"]


def reported_covering_values() -> list[dict]:
    """The register's rows, with each frozen artifact's atom count and mass recomputed.

    The masses are read out of the frozen JSON at render time rather than written into
    the table by hand, so no row can quote a figure the artifact beside it does not
    have. A path that no longer resolves raises rather than rendering a blank cell:
    this table's subject is what the repository retains, and a vanished artifact is a
    change to that answer, not a missing detail. ``mass`` is that recomputed mass, or
    ``None`` where nothing was frozen.
    """
    out = []
    for row in covering_value_register():
        artifact = row["frozen_artifact"]
        mass = None
        if artifact is None:
            evidence = f"nothing frozen here. {row['notes']}"
        else:
            record, mass = load_certificate(REPO / artifact)
            evidence = (
                f"frozen {len(record['atoms']):,}-atom certificate, "
                f"feasible mass {float(mass):.6f}. {row['notes']}"
            )
        out.append(
            {
                "n": row["n"],
                "side": row["side_decimal"],
                "exact_side": Fraction(row["side"]),
                "site_set": row["site_set"],
                "reported": row["objective"],
                "converged": row["converged"],
                "stop_reason": row["stop_reason"],
                "mass": mass,
                "evidence": evidence,
            }
        )
    return out


def sides_named(sides: list[str]) -> str:
    """``3.96``, ``4.58`` and ``4.59``: a list of sides as the prose quotes them."""
    quoted = [f"`{side}`" for side in sides]
    if len(quoted) <= 1:
        return "".join(quoted)
    return ", ".join(quoted[:-1]) + " and " + quoted[-1]


def retained_certificates() -> list[dict]:
    """Every retained first-party certificate, found by globbing the case packages.

    A case package's own ``__main__.py`` always replays ``certificate.json`` as the
    rung currently in force -- every package's ``replay.py`` sets
    ``CERTIFICATE_PATH = Path(__file__).with_name("certificate.json")``, and a
    package that also keeps a weaker historical rung stores it under a different
    filename (``certificate-<side>.json``), never this one. So globbing straight to
    that filename, rather than importing each package's Python, finds exactly the
    rungs the register currently holds.

    The row is keyed by ``least_size_certified``, not by the JSON's own ``n`` field.
    Condition 2 of the certificate mentions only ``n``, so a certificate of mass ``M``
    certifies every integer above ``M``, and the case it moves first is the least of
    them -- which need not be the ``n`` the package is named for. The n = 20 package
    is the worked example in both directions: while its retained rung was the 24/5
    one, mass 946131/50000 = 18.922620, this document keyed it to ``n = 19``; the
    97/20 rung that replaced it has mass 19848723/1000000 = 19.848723 and keys it to
    ``n = 20``. Nothing here depends on which of those is current.
    """
    rows = []
    for path in sorted(CASES.glob("n*_fractional_certificate/certificate.json")):
        record, total_mass = load_certificate(path)
        outer_side = Fraction(str(record["outer_side"]))
        rows.append(
            {
                "package": path.parent.name,
                "n": least_size_certified(total_mass),
                "lower": float(outer_side),
            }
        )
    return rows


def measured_attainment(rows: list[dict]) -> list[dict]:
    """Join every retained certificate against its case's ceiling and best packing.

    ``rows`` is `cases`'s output. A retained certificate's own target ``n`` (from
    `retained_certificates`) picks the row that carries its ceiling and best known
    packing, exactly as every other figure in this document is derived rather than
    looked up by hand. ``binds`` names whichever of the two is the tighter cap, and
    ``ratio`` is the retained lower bound divided by that binding value -- against
    the best packing where the packing binds, against the ceiling where it does not.
    """
    by_n = {row["n"]: row for row in rows}
    out = []
    for cert in retained_certificates():
        case = by_n[cert["n"]]
        best_packing = case["upper"]
        ceiling = case["ceiling"]
        lower = cert["lower"]
        if best_packing is None:
            raise ValueError(f"n = {cert['n']}: retained certificate has no best packing")
        if ceiling >= best_packing:
            binds, ratio = "packing", lower / best_packing
        else:
            binds, ratio = "ceiling", lower / ceiling
        out.append(
            {
                "n": cert["n"],
                "package": cert["package"],
                "lower": lower,
                "best_packing": best_packing,
                "ceiling": ceiling,
                "binds": binds,
                "ratio": ratio,
            }
        )
    return sorted(out, key=lambda r: r["n"])


#: How each packing-limited run stopped, keyed by the case it certifies. The section
#: below names only the cases actually in the corpus, so a rung that moves a package
#: from one side of the join to the other drops its sentence rather than stranding it.
#: A case absent from this map is reported as having no stop reason recorded, which is
#: itself the honest statement -- see `D-443`.
STOP_REASONS = {
    11: "n = 11 ran its covering search to a converged optimum.",
    17: (
        "n = 17 has no stop reason recorded for its own build at all -- the stop "
        "narrated in its `next_rung` belongs to an adjacent probe at n = 18, not to "
        "the certificate this row measures."
    ),
    19: (
        "n = 19 was halted at round 9 on projected cost, four rounds short of where "
        "it would have stopped on its own."
    ),
}

_COUNT_WORDS = ("no", "one", "two", "three", "four", "five", "six", "seven", "eight")


def _wrap_sentences(text: str, width: int = 72) -> list[str]:
    """Prose assembled from the corpus, wrapped to the width the document is written at."""
    return textwrap.wrap(text, width=width) or [""]


def count_word(count: int) -> str:
    """``3`` as ``"three"``, for prose that must agree with a number the corpus sets."""
    return _COUNT_WORDS[count] if count < len(_COUNT_WORDS) else str(count)


def mean_packing_ratio(measured: list[dict]) -> float:
    """The mean ``ratio`` over certificates the best packing binds, not the ceiling.

    ``n = 12`` is the case this excludes: its ceiling sits below its best packing, so
    its ratio measures how close the certificate came to the method's own ceiling,
    not to a packing, and averaging it in would mix two different questions.
    """
    packing_bound = [row["ratio"] for row in measured if row["binds"] == "packing"]
    if not packing_bound:
        raise ValueError("no packing-limited retained certificates to average")
    return sum(packing_bound) / len(packing_bound)


def predicted_reach(rows: list[dict], ratio: float) -> list[dict]:
    """Every live row plus what the mean packing ratio would extrapolate to.

    ``predicted`` is ``min(ratio * best_packing, limit)`` -- the mean ratio applied
    to the case's own best packing, capped at the case's limit so the extrapolation
    never claims more than `ceiling_side_for_net` or `packing_side_cap` allows.
    ``predicted gain`` is ``predicted - lower``, clamped at zero: a case already past
    its prediction (as a case with no prize at all would be) gets no negative row.
    A row with no recorded best packing is dropped rather than given a fabricated
    prediction; every live case in the retained register carries one today.
    """
    out = []
    for row in rows:
        best_packing = row["upper"]
        if best_packing is None:
            continue
        predicted = min(ratio * best_packing, row["limit"])
        out.append(
            {
                **row,
                "predicted": predicted,
                "predicted_gain": max(predicted - row["lower"], 0.0),
            }
        )
    return out


def cell(value: float | None) -> str:
    """A four-place table cell, or `—` where the record carries nothing to show."""
    return f"{value:.4f}" if value is not None else "—"


def render(rows: list[dict]) -> str:
    out = [BANNER, "", "# Where the fractional certificate can still go", ""]
    out += [
        "The most a weighted fractional unavoidable-set certificate could add to each",
        "case's lower bound, at the 181-direction net every retained certificate uses.",
        "`ceiling` is `ceil(sqrt(n)) / (1 + D)`, proved in",
        "`sqpack.fractional.certificate.ceiling_side`.",
        "",
        "`cap` is the same argument with the case's best known packing in place of the",
        "grid. Scale that packing, at side `U`, into a container of side `L`: once",
        "`L > U · B · max(cos δ + sin δ)`, with `δ` each tilt's offset from its nearest",
        "net direction, every scaled square holds its own `B`-square at a net direction,",
        "`Condition 5` forces the mass to `n`, and no certificate exists. Over the shrinks",
        "the net admits that is `U · max(cos δ + sin δ) / (1 + D)` — a supremum, as",
        "`ceiling` is, and always strictly below `U`. The argument is",
        "[X-014](../campaign/explorations/X-014-closing-from-both-ends.md)'s, made at",
        "`n = 11`; `devtools.render_certificate_reach.packing_side_cap` computes it from",
        "each record's `tilt_angles_deg`, and a case whose geometry was never imported",
        "has no inventory and shows `—`. `limit` is the smaller of `ceiling` and `cap`,",
        "and `limited by` names what binds: `packing` where the limit clears the best",
        "known packing, otherwise whichever of the two the limit is.",
        "",
    ]
    reported = reported_covering_values()
    sides = sorted({row["exact_side"] for row in reported})
    band = float(sides[-1] - sides[0])
    converged = [row for row in reported if row["converged"]]
    own_mass = sorted(
        {
            row["side"]
            for row in reported
            if row["mass"] is not None
            and f"{float(row['mass']):.4f}" == f"{float(row['reported']):.4f}"
        }
    )
    other_mass = sorted(
        {
            row["side"]
            for row in reported
            if row["mass"] is not None
            and f"{float(row['mass']):.4f}" != f"{float(row['reported']):.4f}"
        }
    )
    out += [
        "**`prize` is what the limit allows, not what a search will reach.** The real",
        "limit is the covering value: a certificate exists at side `L` only where the",
        "least total mass that covers every admissible `B`-square falls below `n`, and",
        f"that value can bind well below either cap. {len(reported)} restricted optima",
        f"have been reported at {len(sides)} sides, one per site set, and",
        "`frontier/covering-values.yaml` registers each with whether its row loop",
        "converged; every one is at best an upper bound on the unrestricted covering",
        "value there. What survives here beside each is a frozen certificate or nothing",
        "at all:",
        "",
        (
            "| n | side | site set | reported value | converged | stopped because |"
            " evidence retained here |"
        ),
        "| ---: | ---: | --- | ---: | --- | --- | --- |",
    ]
    out += [
        f"| {row['n']} | {row['side']} | {row['site_set']} | {row['reported']} | "
        f"{'yes' if row['converged'] else 'no'} | {row['stop_reason']} | {row['evidence']} |"
        for row in reported
    ]
    out += [
        "",
        "No covering-search run log or solver checkpoint was retained for any of them, so",
        "not one of the reported values can be recomputed here. What a frozen certificate",
        "recomputes is its own feasible mass — a total that covers every admissible",
        "`B`-square at that side, and so an upper bound on the covering value there,",
        f"rather than the objective a search reported. Only at {sides_named(own_mass)} is",
        f"the reported value the artifact's own mass; at {sides_named(other_mass)} the",
        "artifact's mass and the reported objective are different numbers.",
        "",
        "They are also reports of different kinds rather than one series measured the same",
        f"way, and the `converged` column is where the difference lives: {len(converged)} of",
        f"the {len(reported)} ran their row loop to convergence, and the rest stopped for the",
        "reason beside each — or for none the record kept — and stand as upper bounds on",
        f"their own site sets only. {len(reported)} heterogeneous reports across a side band",
        f"{band:.2f} wide do not support a growth trend or a fitted curve, and no rung in",
        "this register has ever been claimed from one. Rank on `prize` to choose where to",
        "look; measure and retain the run before believing any extrapolation.",
        "",
    ]
    live = [r for r in rows if r["verdict"] != "foreclosed"]
    dead = [r for r in rows if r["verdict"] == "foreclosed"]
    by_ceiling = [r for r in dead if r["bound"] == "ceiling"]
    by_cap = [r for r in dead if r["bound"] == "cap"]
    out += [
        f"Of {len(rows)} registered cases, {len(dead)} are foreclosed and {len(live)} are",
        f"not. {len(by_ceiling)} of the foreclosed sit at the grid bound `ceil(sqrt(n))`,",
        "which is where the refuting grid fits — so that foreclosure costs nothing except",
        "where the case is open and its conjectured value is that bound.",
    ]
    if by_cap:
        named = ", ".join(str(r["n"]) for r in by_cap)
        out += [
            f"The other {len(by_cap)} — n = {named} — are foreclosed by their own packing:",
            "the cap sits strictly below the best known packing, and here at or below the",
            "lower bound, so nothing was on offer.",
        ]
    out += [
        "",
        "## Ranked by prize",
        "",
        "| n | m | lower | best packing | ceiling | cap | limit | limited by | prize |",
        "| ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | ---: |",
    ]
    for r in sorted(live, key=lambda r: -r["prize"]):
        out.append(
            f"| {r['n']} | {r['order']} | {r['lower']:.4f} | {cell(r['upper'])} | "
            f"{r['ceiling']:.4f} | {cell(r['cap'])} | {r['limit']:.4f} | {r['verdict']} | "
            f"{r['prize']:+.4f} |"
        )

    measured = measured_attainment(rows)
    ratio = mean_packing_ratio(measured)
    out += [
        "",
        "## Measured attainment",
        "",
        "Every retained first-party fractional certificate, joined against its case's",
        "best packing and ceiling. `ratio` is the retained lower bound divided by",
        "whichever of the two `limited by` names -- the only honest denominator, since",
        "the other one was never in reach.",
        "",
        "| n | package | retained lower bound | best packing | ceiling | limited by | ratio |",
        "| ---: | --- | ---: | ---: | ---: | --- | ---: |",
    ]
    for r in measured:
        out.append(
            f"| {r['n']} | {r['package']} | {r['lower']:.4f} | {r['best_packing']:.4f} | "
            f"{r['ceiling']:.4f} | {r['binds']} | {r['ratio']:.5f} |"
        )
    limited = [r for r in measured if r["binds"] == "packing"]
    word = count_word(len(limited))
    named = ", ".join(f"n = {r['n']}" for r in limited)
    spread = max(r["ratio"] for r in limited) - min(r["ratio"] for r in limited)
    stops = " ".join(
        STOP_REASONS.get(r["n"], f"n = {r['n']} has no stop reason recorded.") for r in limited
    )
    out += [
        "",
        f"## What {word} points would predict, if the ratio held",
        "",
        f"**This is an extrapolation from {word} points, not a measurement.** The {word}",
        f"packing-limited rows above -- {named} -- land inside a band",
        f"{spread:.5f} wide, and their mean is the `ratio` this section's numbers all",
        f"come from: `{ratio:.5f}`. That the {word} numbers are exact rationals decided",
        "by an exact verifier does not make their mean a rate. No rung in this register",
        "has ever been claimed from a fitted curve, and this one is not the exception:",
        "it is offered here as a place to look, not as a result.",
        "",
        "The ratio is also not purely about how good a covering value the method can",
        "reach -- it is an observation about where searches were stopped as much as",
        f"about where they could go. The {word} runs behind it did not stop for the",
        "same reason, and not every reason is a statement about the method.",
        *_wrap_sentences(stops),
        f"A ratio built from {word} runs, at least one of which is not known to have",
        "gone as far as it could, is not a rate to spend a rung's confidence on",
        "(`D-443`).",
        "",
        "`predicted` below is `min(ratio * best_packing, limit)` and `predicted",
        "gain` is `predicted - lower`, clamped at zero. Read them as where to look",
        "next, never as a result standing in for one: the number to act on when a",
        "case is actually run is still the restricted optimum a converged search",
        "reaches, not this extrapolation.",
        "",
        "## Ranked by predicted gain",
        "",
        (
            "| n | m | lower | best packing | ceiling | cap | limit | limited by | prize"
            " | predicted | predicted gain |"
        ),
        "| ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | ---: | ---: | ---: |",
    ]
    for r in sorted(predicted_reach(live, ratio), key=lambda r: -r["predicted_gain"]):
        out.append(
            f"| {r['n']} | {r['order']} | {r['lower']:.4f} | {cell(r['upper'])} | "
            f"{r['ceiling']:.4f} | {cell(r['cap'])} | {r['limit']:.4f} | {r['verdict']} | "
            f"{r['prize']:+.4f} | {r['predicted']:.4f} | {r['predicted_gain']:+.4f} |"
        )
    out += ["", "## Foreclosed", ""]
    out += [
        "| n | m | lower | ceiling | cap | foreclosed by |",
        "| ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    for r in dead:
        out.append(
            f"| {r['n']} | {r['order']} | {r['lower']:.4f} | {r['ceiling']:.4f} | "
            f"{cell(r['cap'])} | {r['bound']} |"
        )
    out += [
        "",
        "<!-- This document follows common-doc-guidelines.md.",
        "See github.com/jlevy/practical-prose and review guidelines before editing.",
        "-->",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift, write nothing")
    args = parser.parse_args()
    text = render(cases())
    if args.check:
        if not OUT.exists() or OUT.read_text() != text:
            name = OUT.relative_to(ROOT.parent)
            print(f"{name} is stale; run devtools.render_certificate_reach")
            return 1
        return 0
    with atomic_output_file(OUT) as tmp:
        tmp.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
